import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useRef } from 'react';
import grapesjs from 'grapesjs';
import pluginBlockBasic from 'grapesjs-blocks-basic';
import 'grapesjs/dist/css/grapes.min.css';
import 'grapesjs/dist/grapes.min.js';

export default function Home() {
  const editor = useRef(null);

  useEffect(() => {
    if (editor.current) {
      return;
    }

    editor.current = grapesjs.init({
      container: '#gjs',
      selectable: false,
      highlightable: false,
      badgable: false,
      hoverable: false,
      showOffsets: 0,
      noticeOnUnload: 0,
      fromElement: true,
      storageManager: false,
      dragMode: 'absolute',
      plugins: [pluginBlockBasic],
    });

    window.editor = editor.current;
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div id='gjs'></div>
      </main>
    </div>
  );
}
